name: Save CSV File

on:
  workflow_dispatch:
    inputs:
      participant_id:
        description: 'Last 4 digits of Participant ID'
        required: true
        type: string

jobs:
  save-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install github

      - name: Generate and save CSV
        run: |
          # Run the Python script to generate the CSV file with participant ID
          python generate_csv.py ${{ github.event.inputs.participant_id }}

      - name: Commit CSV to GitHub
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add data/*.csv
          git commit -m "Add participant CSV file"
          git push
